name: test_workflow_docker
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
env:
  DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: build docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/pyapp:v${{ github.run_number }}  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: push-to-dockerhub
        run: docker image push ${{ env.DOCKERHUB_USERNAME }}/pyapp:v${{ github.run_number}}
#   deploy:
#     runs-on: ubuntu-latest
#     container:
#       image: 





