name: test_workflow_docker
on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
env:
  DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: build and tag
        run: | 
          docker image build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/pyapp:v${{ github.run_number }}
          docker image tag ${{ env.DOCKERHUB_USERNAME }}/pyapp:v${{ github.run_number }} ${{ env.DOCKERHUB_USERNAME }}/pyapp:latest
      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: push-to-dockerhub
        run: | 
          docker image push ${{ env.DOCKERHUB_USERNAME }}/pyapp:v${{ github.run_number}}
          docker image push ${{ env.DOCKERHUB_USERNAME }}/pyapp:latest
  deploy:
    runs-on: ga-aws #self-hosted
    steps:
       - name: deploy_app
         run: |
           docker container run -d --name pyapp ${{ env.DOCKERHUB_USERNAME }}/pyapp:latest





